#!/bin/sh

# Misc variables for line breaks and color
LINE="\n#############"
COLOR_YELLOW='\033[0;33m'
COLOR_RESET='\033[0m'

# SSH into remote server and archive database
ssh $REMOTE_SERVER "cd $REMOTE_PATH && 
    mysqldump -u $REMOTE_USER_NAME --password=\"$REMOTE_MYSQL_PASSWORD\" -h $REMOTE_HOST_NAME --port=$REMOTE_PORT $REMOTE_DB_NAME > $FILE_NAME";

echo "${COLOR_YELLOW}$LINE\nArchived database${COLOR_RESET}\n";

cd /app;

scp $REMOTE_SERVER:$REMOTE_PATH/$FILE_NAME .;

echo "${COLOR_YELLOW}$LINE\nCopied $FILE_NAME from $REMOTE_SITE_NAME to $LOCAL_PATH${COLOR_RESET}\n";

ssh $REMOTE_SERVER "cd $REMOTE_PATH && rm $FILE_NAME";

echo "${COLOR_YELLOW}$LINE\nDeleted $FILE_NAME from $REMOTE_SITE_NAME${COLOR_RESET}\n";

wp db import $FILE_NAME;

echo "${COLOR_YELLOW}$LINE\nImported $FILE_NAME into local database${COLOR_RESET}\n";

wp search-replace --all-tables $REMOTE_SITE_NAME $LOCAL_SITE_NAME

echo "${COLOR_YELLOW}\n$LINE\nUpdated the wp_options table by replacing all references of $REMOTE_SITE_NAME with $LOCAL_SITE_NAME${COLOR_RESET}\n";
